name: win7-llama-server

on:
  workflow_dispatch:

jobs:
  build-mingw:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Build llama-server (static, Win7)
        shell: msys2 {0}
        run: |
          mkdir build && cd build
          export CFLAGS="-O2 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000"
          export CXXFLAGS="$CFLAGS -static-libgcc -static-libstdc++"
          export LDFLAGS="-static -static-libgcc -static-libstdc++ -Wl,--major-subsystem-version,6 -Wl,--minor-subsystem-version,1"

          cmake .. \
            -G "MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLAMA_BUILD_SERVER=ON \
            -DLLAMA_CURL=OFF \
            -DGGML_CUDA=OFF -DGGML_VULKAN=OFF

          cmake --build . --config Release --target llama-server -- -j4
          strip bin/llama-server.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama-server-win7-static
          path: build/bin/llama-server.exe
