name: win7-llama-server-msvc

on:
  workflow_dispatch:

jobs:
  build-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Configure (MSVC, static runtime, Win7)
        shell: cmd
        run: |
          cmake -S . -B build-msvc -G "Visual Studio 17 2022" -A x64 ^
            -DLLAMA_BUILD_SERVER=ON ^
            -DLLAMA_CURL=OFF ^
            -DGGML_CUDA=OFF ^
            -DGGML_VULKAN=OFF ^
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ^
            -DCMAKE_C_FLAGS="/D_WIN32_WINNT=0x0601 /DNTDDI_VERSION=0x06010000" ^
            -DCMAKE_CXX_FLAGS="/D_WIN32_WINNT=0x0601 /DNTDDI_VERSION=0x06010000" ^
            -DCMAKE_EXE_LINKER_FLAGS="/SUBSYSTEM:CONSOLE,6.01"

      - name: Build (Release)
        run: cmake --build build-msvc --config Release --target llama-server --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama-server-win7-msvc-static
          path: build-msvc/bin/Release/llama-server.exe
